language: smalltalk
sudo: required

os:
  - linux
#  - osx OSX doesn't come with a mongodb service

services:
  - mongodb # Essential to what we do
  - docker

# Target mongodb v3.0 as lowest version
addons:
  apt:
    sources:
    - mongodb-3.0-precise
    packages:
    - mongodb-org-server

smalltalk:
  - Pharo-4.0
  - Pharo-5.0

before_install:
  - sudo dpkg --add-architecture i386
  - sudo apt-get update -yy
  - sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install libc6:i386 libuuid1:i386 libfreetype6:i386 libssl1.0.0:i386

script:
  - $SMALLTALK_CI_HOME/run.sh
  - wget -O- http://travis.debian.net/script.sh | sh -
