language: smalltalk
sudo: required

os:
  - linux
#  - osx OSX doesn't come with a mongodb service

services:
  - mongodb # Essential to what we do
  - docker

# Target mongodb v3.0 as lowest version
addons:
  apt:
    sources:
    - mongodb-3.0-precise
    packages:
    - mongodb-org-server

before_install:
  - sudo apt-get install -yy --no-install-recommends -o Dpkg::Options::="--force-confdef" docker-engine

smalltalk:
  - Pharo-4.0
  - Pharo-5.0

script:
  - $SMALLTALK_CI_HOME/run.sh .smalltalk.ston
  - cp $SMALLTALK_CI_HOME/_builds/TravisCI.changes OsmoSmsc.changes
  - cp $SMALLTALK_CI_HOME/_builds/TravisCI.image OsmoSmsc.image
  - bash docker/docker-image.sh
  - bash integration-tests/integration-tests.sh
  - sh ./docker/debian-build.sh

after_failure:
  - bash integration-tests/after_failure.sh
