language: smalltalk
sudo: required

os:
- linux
#  - osx OSX doesn't come with a mongodb service

services:
- mongodb # Essential to what we do
- docker

# Target mongodb v3.0 as lowest version
addons:
  apt:
    sources:
    - mongodb-3.0-precise
    packages:
    - mongodb-org-server

before_install:
- sudo apt-get install -yy --no-install-recommends -o Dpkg::Options::="--force-confdef"
  docker-engine osc rpm-common rpm

smalltalk:
- Pharo-4.0
- Pharo-5.0

script:
- set -e
- $SMALLTALK_CI_HOME/run.sh
- cp $SMALLTALK_CI_HOME/_builds/TravisCI.changes OsmoSmsc.changes
- cp $SMALLTALK_CI_HOME/_builds/TravisCI.image OsmoSmsc.image
- bash docker/docker-image.sh
- bash integration-tests/integration-tests.sh
- sh ./docker/debian-build.sh
- bash deploy/deploy.sh

after_failure:
- bash integration-tests/after_failure.sh
- bash deploy/after_failure.sh

env:
  global:
   - secure: 3DlmSCgPjzcP8hsUZSvdK89giHniXvK2fnybCCSpjusjvMChKu1F+B9tmGyDMDxF3MXYNAUaTpCJdy4mn/zhj9VJFRIApoNVZqwac7zYNRW/xKBiYQ+QMKV1Jo8dXpkHTfu3nl5y6vRfBwqke0xCQe2sG13rHMr+Hhh5KXYf7fSmvJZZoXuPX4t365xr+7nMyJ0GUOWfKtIgjPXqv11pqkPiBlRtqBOgGBSc/218rEiyREGIGaJpyXQNiXuc4HE8CavIZok7csd9Hl2u0XSZIWWYviJVq+8usgLDZguMLLyn3oVmzMbV1ah1wSjygHTGgexfVcvpng//wAQCxpJ8yG2ThAP7zBsdJUERfQblS1r/9Sn18R7agR0UXPgDvS8n4ugnolgHJwKKN+N25oLzKyu+LJXQWJxvG24fE5voqvuU4GV7dtCHjUaccup0tnhMivL/nCwz/7Wo+ad3KGKclsw6ba+MFHJ+PJJU4GMY+IlkWJIP4g/hlHhoYWIypvmnr5aX/uIwmKnmwfV8fGs4r+Qdir04ouLHJ/1SRmrsL0vAMywZ7BzkfoMnCQ2sokjIS4x7AWtZ/YXITwQhYbflj+7LU1jw/CLkOeh2p6sKu2ODgV2UTTtgBsYabp+r8IVoffkqgFDY3ZVpI2q0YVBnZcCPrgRxNZr+agFNzGjmqRI=
   - secure: ygqhX7xQf4ZCwGvih+6Bs13rDfxF+D6UqCLGbBYzVnctbs7wQjY5UrQALfpDSM15KsaZVBzJQangrRL7zvqMonRRZT4vR/yfhW6CixnEEIsoqAyZ9Kf8sL6NbwfrGw0ZgIzXoGnORYD3uSf+56MObLEPeLOesATYg9AxL3TWBVVmh3Np61OPRjYqaLfZM6H+e2cc86DPHBTTAgXYgq8+nHemGybo1BW4WFWWsf11WoiN8t6s+petulesENeHDanulKD2pbZqNCHKEtY79q17801PhCB/FS3AFmU52uVGgJZglLMmawgx+BawRBycBPFlaT1U6z3ChnIJgFsVF8YoHkkWpwwtDk6ghXbT3Sc2t7DQ2p3KJJU3bW5JWuw0sl2M2sVdhJJ9WQno5eYix/aoCyzZTNOZHJMby2dVtn6k6/4OfYGWGaAX+Wm0hNbuvQ2kAWRC/93ARKyQMa9DDMdzBWG/69euzkrLg7ne3+rOss0oICtCOACwxyfJDnWDVclBGkIBBqxen3f2JNEDK7k6D8E3Vj2oFHId1L03zKzPRkk31Y2Ob7LJoBlHDhyskyegVRZOm5IA64cji1NVo0wqjuQXd2DPvt111G2XnTGlo/0mZBdXMixIaBP1LtVrmcsUV8uYN/nLpA/usWaLveXUnXzmkYz7J27p1ToecGgoK1g=
