language: smalltalk
sudo: false

os:
  - linux
#  - osx OSX doesn't come with a mongodb service

services:
  - mongodb # Essential to what we do

# Target mongodb v3.0 as lowest version
addons:
  apt:
    sources:
    - mongodb-3.0-precise
    packages:
    - mongodb-org-server

smalltalk:
  - Pharo-4.0
  - Pharo-5.0
